# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target '今日头条' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for 今日头条
pod 'AFNetworking'
pod 'SDWebImage'
pod 'Masonry'
pod 'FMDB'
pod 'SVProgressHUD-FE'
end
